### ISSUE TITLE
Picture is not transferred correctly when any chunk is received twice

### ISSUE THREAD

**Issue by Anty0** [SMerrony/tello#10]
## Expected Behavior
Picture is successfully received even when flying in area with heavy signal interference.

## Current Behavior
It is almost impossible to capture picture in locations with high signal interference, due to bug I have discovered and fixed in [this](https://github.com/Anty0/tello/commit/875712f961f5888be8968a5608cadf4ad1e373da) commit. (But unfortunately this commit contains also another improvements for communication, so it isn't easy to see, where exactly the fix is.)

Current implementation of picture transfer is counting every received chunk and rejects all chunks when piece already have received 8 chunks. In situation, where any chunk is received twice, there will be some chunks missing in that piece. As result whole image is not saved.

## Possible Solution
Move this line in tello.go (on line 347):
`tello.fileTemp.pieces[thisChunk.pieceNum].numChunks++`

To the inside of `if` body on line 342:
`if !already {`

This causes only properly received chunks to be counted and (so far during my testing) every image to be received.

## Steps to Reproduce (for bugs)

1. Connect to tello
2. Take some pictures (10+)
3. Save pictures
4. Disconnect from tello
5. Some pictures might be missing based on interference between drone and your WiFi adapter

## Your Environment

* Go Version used: `go version go1.11.5 linux/amd64`
* Tello Package Version or Date: [401f34d](https://github.com/SMerrony/tello/commit/401f34d478d3c55c71dae2e818ef12e135a34cb0)
* Operating System and version: Arch Linux

**Comment by SMerrony** [comment]
Thanks so much for this report and fix suggestion.  Just committed it and will test soon and do a release forthwith.

Would you like to share any of the other comms improvements?

**Comment by Anty0** [comment]
I was thinking about sharing my improvements since I started working on them. Unfortunately I didn't have enough time to do so yet...
Once I find some time, I'll recommit them in separate and more clean commits and create pull requests, but feel free to use some obvious changes on your own, in case you find some time faster then me. :)
