### ISSUE TITLE
Python wrapper for repo

### ISSUE THREAD

**Issue by arsh09** [SMerrony/tello#11]
Hello, 

First of all, thank you for your github. 

Sadly, I do not know how to use Go, that is why I wanted to ask if there is any Python wrapper for this git that you know of? or if anyone has implemented this. 

Thank you 

Arshad

**Comment by SMerrony** [comment]
There is a list of APIs - including a couple of Python ones at: https://tellopilots.com/wiki/development/

It would not make sense to wrap a Python API around this Go one.
