### ISSUE TITLE
Land command appears to be ignored

### ISSUE THREAD

**Issue by a34729t** [SMerrony/tello#12]
I tried running telloterm and using your library and ran into the same issue- if I send a takeoff command and then a land command even a few seconds later, the land command is ignored. In the basic example you provide, takeoff, wait 10s and land works, but as soon as I try less time- say 1s or 3s- the land command is ignored.

I'm going to implement the basic UDP comms and see if I can replicate this.

Here's the exact code I'm using:

```
package main

import (
	"fmt"
	"log"

	"github.com/SMerrony/tello"
)

func basicTakeOffAndLandingDemo() {
	fmt.Println("Demo: Connect, takeoff, hover, land")
	fmt.Println("Connecting to drone...")

	drone := new(tello.Tello)
	err := drone.ControlConnectDefault()
	if err != nil {
		log.Fatalf("%v", err)
	}

	drone.TakeOff()
	time.Sleep(3 * time.Second) // 1 second doesn't work
	drone.Land()
	drone.ControlDisconnect()

	fmt.Println("Disconnected from drone...")
}

func main() {
	basicTakeOffAndLandingDemo()
}
```

**Comment by SMerrony** [comment]
I don't think this is an issue with my tello package - the Tello is simply not accepting the land command until it has finished doing other things.
