### ISSUE TITLE
Autopilot wrong direction

### ISSUE THREAD

**Issue by thaiacepilot** [SMerrony/tello#3]
## Possible Solution

 maybe add Autofly (direction,distance) like scratch or python but can adjust speed ( more than 1m/s ) and more range (more than 5 m) like now

## Context
 many times

## Your Environment

* Go Version used: 1.10.3
* Tello Package Version or Date:  V1.03.33.01
* Operating System and version: Windows 10 pro build 1803

**Comment by thaiacepilot** [comment]
my code for simple testing
`package mission
import (
  "time"
  "github.com/SMerrony/tello"
)
func Basic() {
  drone := new(tello.Tello)
  drone.ControlConnectDefault()
  drone.TakeOff()
  time.Sleep(5 * time.Second)
  drone.SetHome()
  time.Sleep(1 * time.Second)
  drone.AutoFlyToXY(0, 2)
  time.Sleep(1 * time.Second)
  drone.AutoFlyToXY(0, 0)
  time.Sleep(2 * time.Second)
  drone.Land()
 
}
`

**Comment by SMerrony** [comment]
You don't actually say above what your problem is.

Anyway, if you checked the error returns from the drone funcs then you might see what your problem is.
