### ISSUE TITLE
gRPC support

### ISSUE THREAD

**Issue by filippobottega** [SMerrony/tello#5]
Hello,
  I'd like to use tello library from C# or VB.NET. I think that [gRPC](https://grpc.io) may be a solution to consume this library from a .NET desktop application.
  What do you think about implementing a gRPC server?

  Thank you,
    Filippo.

**Comment by SMerrony** [comment]
My instinct is that this would be overkill.

Could you not simply use the C# library already available here? - https://github.com/Kragrathea/TelloLib

**Comment by filippobottega** [comment]
Hello,
  you are right, when I have opened the issue I didn't know TelloLib. Yesterday I have tested TelloLib and I was able to takeoff my drone.

  In my opinion is not a good thing develop the same library in two languages just because the need to maintain the same code twice. I prefer write once and use multiple times. But I agree that using only one language simplify the architecture.

  Thank you for your work and your answer,
    Filippo.
