### ISSUE TITLE
Tello doesn't takeoff

### ISSUE THREAD

**Issue by filippobottega** [SMerrony/tello#7]
## Expected Behavior
Hello,
  I'have connected my laptop to Tello network and I run the demo code using the debug:

```
package main
import (
  "log"
  "time"
  "github.com/SMerrony/tello"
)

func main() {
  	drone := new(tello.Tello)
  err := drone.ControlConnectDefault()
  if err != nil {
    log.Fatalf("%v", err) 
  }

  drone.TakeOff()
  time.Sleep(10 * time.Second)
  drone.Land()
  drone.ControlDisconnect()
}
```

## Current Behavior
I have no errors from the execution but Tello drone didn't takeoff.

## Your Environment

* Go Version used: go version go1.10.3 windows/amd64
* Tello Package Version or Date: 31/07/2018
* Operating System and version: Windows 10 1083

**Comment by SMerrony** [comment]
The most likely explanation is that the Tello didn't have enough battery to take off.  I have noticed that if the battery level is below the set threshold then it will refuse to take off even though it could theoretically fly for a little while.

If that's not the problem get back to me...
